explorer/urls.py
from django.urls import path

from .views import BlockList, BlocksByHeight, BlockDetail, Search
from .charts import block_chart, fee_chart


urlpatterns = [
    path("", BlockList.as_view(), name="block-list"),
    path("chart/block", block_chart, name="block-chart"),
    path("chart/fee", fee_chart, name="fee-chart"),
    path("block/<int:height>", BlocksByHeight.as_view(), name="blocks-by-height"),
    path("block/<str:pk>", BlockDetail.as_view(), name="block-detail"),
    path("search", Search.as_view(), name="search"),
]

grinexplorer/urls.py
from django.urls import include, path


urlpatterns = [
    path("", include("explorer.urls")),
]

blockchain/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

SECOND_POW_EDGE_BITS = 29
BASE_EDGE_BITS = 24


def graph_weight(edge_bits):
    # Compute weight of a graph as number of siphash bits defining the graph
    return (2 << edge_bits-BASE_EDGE_BITS)*edge_bits


def scaled_difficulty(hash, graph_weight):
    # Difficulty achieved by this proof with given scaling factor
    diff = ((graph_weight) << 64) / int(hash[:16], 16)
    return min(diff, 0xffffffffffffffff)


def from_proof_adjusted(hash, edge_bits):
    # Computes the difficulty from a hash. Divides the maximum target by the
    # provided hash and applies the Cuck(at)oo size adjustment factor
    # scale with natural scaling factor
    return scaled_difficulty(hash, graph_weight(edge_bits))


def from_proof_scaled(hash, secondary_scaling):
    # Same as `from_proof_adjusted` but instead of an adjustment based on
    # cycle size, scales based on a provided factor. Used by dual PoW system
    # to scale one PoW against the other.
    # Scaling between 2 proof of work algos
    return scaled_difficulty(hash, secondary_scaling)


class Block(models.Model):
    hash = models.CharField(
        max_length=64,
        db_index=True,
        primary_key=True,
    )

    version = models.IntegerField()

    height = models.IntegerField(
        db_index=True,
    )

    previous = models.ForeignKey(
        related_name="children_set",
        to="Block",
        on_delete=models.PROTECT,
        db_index=True,
        null=True,
    )

    prev_root = models.CharField(max_length=64)

    timestamp = models.DateTimeField()

    output_root = models.CharField(max_length=64)

    range_proof_root = models.CharField(max_length=64)

    kernel_root = models.CharField(max_length=64)

    nonce = models.TextField()

    edge_bits = models.IntegerField()

    cuckoo_solution = ArrayField(models.BigIntegerField())

    difficulty = models.IntegerField()

    # sum of the target difficulties, not the sum of the actual block difficulties
    total_difficulty = models.BigIntegerField()

    secondary_scaling = models.IntegerField()

    total_kernel_offset = models.CharField(max_length=64)

    @property
    def difficulty(self):
        # Maximum difficulty this proof of work can achieve
        # 2 proof of works, Cuckoo29 (for now) and Cuckoo30+, which are scaled
        # differently (scaling not controlled for now)
        if (self.edge_bits == SECOND_POW_EDGE_BITS):
            return int(from_proof_scaled(self.hash, self.secondary_scaling))
        else:
            return int(from_proof_adjusted(self.hash, self.edge_bits))

    @property
    def target_difficulty(self):
        if self.previous is None:
            return None
        return self.total_difficulty - self.previous.total_difficulty

    @property
    def reward(self):
        return 60

    @property
    def fees(self):
        return sum(self.kernel_set.all().values_list("fee", flat=True))


class Input(models.Model):
    block = models.ForeignKey(
        to=Block,
        on_delete=models.PROTECT,
        db_index=True,
    )

    data = models.CharField(max_length=66)


class Output(models.Model):
    OUTPUT_TYPE = (
        ("Transaction", "Transaction"),
        ("Coinbase", "Coinbase"),
    )

    block = models.ForeignKey(
        to=Block,
        on_delete=models.PROTECT,
        db_index=True,
    )

    output_type = models.TextField(
        choices=OUTPUT_TYPE
    )

    commit = models.CharField(max_length=66)

    spent = models.BooleanField()

    proof = models.TextField(null=True)

    proof_hash = models.CharField(max_length=64)

    block_height = models.IntegerField(null=True)

    merkle_proof = models.TextField(null=True)
    
    mmr_index = models.IntegerField(null=True)

class Kernel(models.Model):
    block = models.ForeignKey(
        to=Block,
        on_delete=models.PROTECT,
        db_index=True,
    )

    features = models.TextField()

    fee = models.IntegerField()

    lock_height = models.IntegerField()

    excess = models.CharField(max_length=66)

    excess_sig = models.CharField(max_length=142)

explorer/models.py
from django.db import models

# Create your models here.

explorer/views.py
from django.db.models import Count, Sum, Max, Min
from django.db.models.functions import TruncDay
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import redirect

from blockchain.models import Block, Output
from chartit import DataPool, Chart


class BlockList(ListView):
    template_name = "explorer/block_list.html"
    context_object_name = "block_list"

    queryset = Block.objects.order_by("-timestamp")
    paginate_by = 20

    def get_block_chart(self):
        blockpivotdata = DataPool(
            series=[{
                'options': {
                    'source': Block.objects.raw("select 1 as hash, to_char(timestamp,'MM-dd') as niceday, "
                                                "max(total_difficulty) as total_difficulty, "
                                                "date(DATE_TRUNC('day', timestamp)) as date, count(hash) as num "
                                                "from blockchain_block "
                                                "group by DATE_TRUNC('day', timestamp),niceday order by date")
                },
                'terms': [
                    'niceday',
                    'num',
                    'total_difficulty',
                ]
            }]
        )

        blockpivcht = Chart(
            datasource=blockpivotdata,
            series_options=[{
                'options': {
                    'type': 'line',
                    'xAxis': 0,
                    'yAxis': 0,
                    'zIndex': 1,
                    'legendIndex': 1,
                },
                'terms': {
                    'niceday': ['num']
                }}, {
                'options': {
                    'type': 'line',
                    'xAxis': 1,
                    'yAxis': 1,
                    'legendIndex': 0,
                },
                'terms': {
                    'niceday': ['total_difficulty']
                }
            }],
            chart_options={
                'title': {
                    'text': 'Blocks and Total Difficulty'
                },
                'xAxis': [
                    {
                        'title': {
                            'text': 'Date',
                            'style': {
                                'display': 'none'
                            }
                        },
                        'labels': {
                            'enabled': True
                        }
                    },
                    {
                        'title': {
                            'text': 'Date',
                            'style': {
                                'display': 'none'
                            }
                        },
                        'labels': {
                            'enabled': False
                        },
                        'lineColor': 'transparent',
                        'tickLength': 0,
                    }
                ],
                'yAxis': [
                    {
                        'title': {
                            'text': 'Blocks',
                            'style': {
                                'color': '#70b3ef'
                            }
                        },
                        'labels': {
                            'enabled': False
                        },
                    },
                    {
                        'title': {
                            'text': 'Total Diff'
                        },
                        'labels': {
                            'enabled': False
                        }
                    }
                ],
                'legend': {
                    'enabled': False
                },
            }
        )
        return blockpivcht

    def get_fee_chart(self):
        feepivotdata = DataPool(
            series=[{
                'options': {
                    'source': Block.objects.raw("select 1 as hash, to_char(timestamp,'MM-dd') as niceday, "
                                                "date(DATE_TRUNC('day', timestamp)) as date, sum(fee)/1000000 as fee "
                                                "from blockchain_block t1 join blockchain_kernel t2 "
                                                "on t2.block_id=t1.hash "
                                                "group by DATE_TRUNC('day', timestamp),niceday order by date")
                },
                'terms': [
                    'niceday',
                    'fee'
                ]
            }]
        )

        feepivcht = Chart(
            datasource=feepivotdata,
            series_options=[{
                'options': {
                    'type': 'line',
                    'stacking': False
                },
                'terms': {
                    'niceday': [
                        'fee',
                    ]
                }
            }],
            chart_options={
                'title': {
                    'text': 'Transaction Fee Chart'},
                'xAxis': {
                    'title': {
                        'text': 'Date'}},
                'yAxis': {
                    'title': {
                        'text': 'Tx Fee'}},
                'legend': {
                    'enabled': False},
                'credits': {
                    'enabled': False}},
        )
        return feepivcht

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if Block.objects.exists():
            context["highest_block"] = Block.objects.order_by("height").last()
            context["latest_block"] = Block.objects.order_by("timestamp").last()
            context["total_emission"] = Block.objects.order_by("total_difficulty").last().height * 60

            context["competing_chains"] = Block.objects \
                                               .filter(height__gte=context["highest_block"].height - 60) \
                                               .values("height") \
                                               .annotate(cnt=Count("height")) \
                                               .aggregate(Max("cnt"))["cnt__max"]
            context["forked_at"] = Block.objects \
                                        .filter(height__gte=context["highest_block"].height - 60) \
                                        .values("height") \
                                        .annotate(cnt=Count("height")) \
                                        .filter(cnt__gt=1) \
                                        .aggregate(Min("height"))["height__min"]

            context['thumb_chart_list'] = [self.get_block_chart(), self.get_fee_chart()]

        return context


class BlockDetail(DetailView):
    model = Block

    template_name = "explorer/block_detail.html"
    context_object_name = "blk"


class BlocksByHeight(TemplateView):
    template_name = "explorer/blocks_by_height.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["blocks"] = self.blocks
        context["height"] = self.height

        return context

    def get(self, request, height):
        self.blocks = Block.objects.filter(height=height).order_by("-total_difficulty")
        self.height = height

        if len(self.blocks) == 1:
            return redirect("block-detail", pk=self.blocks[0].hash, permanent=False)
        else:
            return super().get(request)


class Search(TemplateView):
    template_name = "explorer/search_results.html"
    results = None
    q_isdigit = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["q"] = self.q
        context["q_isdigit"] = self.q_isdigit
        context["results"] = self.results

        return context

    def get(self, request):
        self.q = request.GET.get("q", "").strip()

        # search query is valid block height
        if self.q.isdigit():
            self.q_isdigit = True

            if Block.objects.filter(height=self.q).count():
                return redirect("blocks-by-height", height=self.q, permanent=False)

        # require at least 8 characters
        if len(self.q) >= 6:
            self.results = Block.objects.filter(hash__startswith=self.q)

            # if only one result, redirect to found block
            if self.results.count() == 1:
                return redirect("block-detail", pk=self.results[0].hash, permanent=False)

        return super().get(request)

explorer/templates/explorer/block_chart.html
{% extends "base.html" %}


{% block chart_loader_header %}
    <!-- code to include the highcharts and jQuery libraries goes here -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
	<script src="https://code.highcharts.com/highcharts.js"></script>
    <!-- load_charts filter takes a comma-separated list of id's where -->
    <!-- the charts need to be rendered to                             -->
	{% load chartit %}
	{{ blockchart|load_charts:"containerblockchart" }}
{% endblock %}


{% block content %}
  <br>

  <div>
        <div class="tag-box tag-box-v2 box-shadow shadow-effect-1" style="margin-bottom: 0px; background-color: #FFFFFF;">
            <div id="containerblockchart" style="min-width: 1024px; height: 480px; margin: 0 auto">
            </div>
        </div>
  </div>

{% endblock %}

explorer/templates/explorer/block_detail.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}
{% load grin %}

{% block content %}
  <br>
  <br>

  <div class="block_detail_header, row">
      <img border="0" src="{% static "images/icons/cube_32x32.png" %}" width="20" height="20" />
      <h4>&nbsp Block {{ blk.height | intcomma }}</h4>
  </div>

  <table class="table table-horizontal-bordered table-hover">
	<tr>
	  <td>Hash</td>
	  <td>{{ blk.hash }}</td>
	</tr>
	<tr>
	  <td>Version</td>
	  <td>{{ blk.version }}</td>
	</tr>
	<tr>
	  <td>Previous Block</td>
	  <td>
		{% if blk.height == 0 %}
		  <em>(None, this is the Genesis Block)</em>
		{% else %}
		  <a href="/block/{{ blk.previous.hash }}" title="{{ blk.previous.hash }}">{{ blk.previous.hash }}</a>
		{% endif %}
	  </td>
	</tr>
	<tr>
	  <td>Age</td>
	  <td>{{ blk.timestamp | date:"Y-m-d, H:i:s" }} UTC</td>
	</tr>
	<tr>
	  <td>PoW Algorithm</td>
	  <td>
	    {% if blk.edge_bits == 29 %}
	    cuckARoo29
	    {% elif blk.edge_bits == 31 %}
	    cuckAToo31
	    {% elif blk.edge_bits == 32 %}
	    cuckAToo32
	    {% endif %}
	  </td>
	</tr>
	<tr>
	  <td>Secondary Scale</td>
	  <td>{{ blk.secondary_scaling | intcomma }}</td>
	</tr>
	<tr>
	  <td>Solution Difficulty</td>
	  <td>{{ blk.difficulty | floatformat:-2 | intcomma }}</td>
	</tr>
	<tr>
	  <td>Target Difficulty</td>
	  <td>{{ blk.target_difficulty | floatformat:-2 | intcomma }}</td>
	</tr>
	<tr>
	  <td>Total Difficulty</td>
	  <td>{{ blk.total_difficulty | intcomma }}</td>
	</tr>
	<tr>
	  <td>Total Kernel Offset</td>
	  <td>{{ blk.total_kernel_offset }}</td>
	</tr>
	<tr>
	  <td>Nonce</td>
	  <td>{{ blk.nonce }}</td>
	</tr>
	<tr>
	  <td>Block Reward</td>
	  <td>{{ blk.reward | grin }}</td>
	</tr>
	<tr>
	  <td>Fees</td>
	  <td>{{ blk.fees | nanogrin }}</td>
	</tr>
  </table>

  <details class="black">
	<summary>Inputs ({{ blk.input_set.all.count }})</summary>

	<table class="table table-horizontal-bordered table-hover">
	  <thead class="thead-light">
		<tr>
		  <th>Commit</th>
		</tr>
	  </thead>
	  <tbody>
		{% for input in blk.input_set.all %}
		  <tr>
			<td style="font-family:monospace;">{{ input.data }}</td>
		  </tr>
		{% endfor %}
	  </tbody>
	</table>
  </details>

  <br>

  <details class="black">
	<summary>Outputs ({{ blk.output_set.all.count }})</summary>

	<table class="table table-horizontal-bordered table-hover">
	  <thead class="thead-light">
		<tr>
		  <th>Output Type</th>
		  <th>Commit</th>
		  <th>Spent</th>
		</tr>
	  </thead>
	  <tbody>
		{% for output in blk.output_set.all %}
		  <tr>
			<td>{{ output.output_type }}</td>
			<td>{{ output.commit }}</td>
			<td>{{ output.spent }}</td>
		  </tr>
		{% endfor %}
	  </tbody>
	</table>
  </details>

  <br>

  <details class="black">
	<summary>Kernels ({{ blk.kernel_set.all.count }})</summary>

	<table class="table table-horizontal-bordered table-hover">
	  <thead class="thead-light">
		<tr>
		  <th>Features</th>
		  <th>Fee</th>
		  <th>Lock Height</th>
		</tr>
	  </thead>
	  <tbody>
		{% for kernel in blk.kernel_set.all %}
		  <tr>
			<td>{{ kernel.features }}</td>
			<td>{{ kernel.fee | nanogrin }}</td>
			<td>{{ kernel.lock_height }}</td>
		  </tr>
		{% endfor %}
	  </tbody>
	</table>
  </details>

{% endblock content %}

explorer/templates/explorer/block_list.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}
{% load grin %}
{% load shortnaturaltime %}

{% block chart_loader_header %}
  {% if block_list.exists %}
	<!-- code to include the highcharts and jQuery libraries goes here -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
	<script src="https://code.highcharts.com/highcharts.js"></script>
	<!-- load_charts filter takes a comma-separated list of id's where -->
	<!-- the charts need to be rendered to                             -->
	{% load chartit %}
	{{ thumb_chart_list|load_charts:"thumbnail_blockchart, thumbnail_feechart" }}
  {% endif %}
{% endblock %}

{% block content %}
  {% if block_list.exists %}
	<br>

	<div class="row align-items-start">
	  <div class="col col-sm-6">
		<a href="/chart/block">
		  <div class="tag-box tag-box-v2 box-shadow shadow-effect-1" style="border-right-color: #3498db; border-right-style: solid; border-right-width: 2px; margin-bottom: 0px; background-color: #FFFFFF;">
			<div id="thumbnail_blockchart" style="min-width: 255px; height: 200px; margin: 0 auto">
			</div>
		  </div>
		</a>
	  </div>
	  <div class="col col-sm-6">
		<a href="/chart/fee">
		  <div class="tag-box tag-box-v2 box-shadow shadow-effect-1" style="border-right-color: #3498db; border-right-style: solid; border-right-width: 2px; margin-bottom: 0px; background-color: #FFFFFF;">
			<div id="thumbnail_feechart" style="min-width: 255px; height: 200px; margin: 0 auto">
			</div>
		  </div>
		</a>
	  </div>
	</div>

	<br>

	<div class="row">
	  <div class="col-sm-6 col-md-3">
		<div class="card">
		  <div class="card-header">
			Chain Height
		  </div>
		  <div class="card-body">
			<h4 class="card-title">{{ highest_block.height | intcomma }}</h4>
		  </div>
		</div>
	  </div>

	  <div class="col-sm-6 col-md-3">
		<div class="card">
		  <div class="card-header">
			Latest Block
		  </div>
		  <div class="card-body">
			<h4 class="card-title">{{ latest_block.timestamp | naturaltime }}</h4>
		  </div>
		</div>
	  </div>

	  <div class="col-sm-6 col-md-3">
		<div class="card" title="Actual vs. Expected Block Difficulty">
		  <div class="card-header">
			Latest Block Difficulty
		  </div>
		  <div class="card-body">
			<h4 class="card-title">
			  {{ latest_block.difficulty | intcomma }} / {{ latest_block.target_difficulty | intcomma }}
			</h4>
		  </div>
		</div>
	  </div>

	  <div class="col-sm-6 col-md-3">
		<div class="card">
		  <div class="card-header">
			Emission
		  </div>
		  <div class="card-body">
			<h4 class="card-title">{{ total_emission | grin }}</h4>
		  </div>
		</div>
	  </div>
	</div>

	<br>

	{% if competing_chains > 1 %}
	  <div class="alert alert-danger" role="alert">
		<strong>Fork detected!</strong>
		We've detected {{ competing_chains | apnumber }} competing chains, forked at <a href="/block/{{ forked_at }}">Block {{ forked_at }}</a>. Stay wary!
	  </div>
	{% endif %}

	{% if block_list %}
	  <div class="row align-items-start">
		<div class="col">
		  <div class="block_detail_header, row">
			<img border="0" src="{% static "images/icons/cubes_32x32.png" %}" width="25" height="25" />
			<h4>&nbsp Blocks</h4>
		  </div>
		</div>
		<div class="col-sm-6 col-md-3" align="center">
		  {% if is_paginated %}
			<ul class="pagination justify-content-center">
			  {% if page_obj.has_previous %}
				<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
			  {% else %}
				<li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
			  {% endif %}
			  <li class="page-item disabled">
				<a class="page-link" href="#">{{ page_obj.number }} / {{ paginator.num_pages }}</a>
			  </li>
			  {% if page_obj.has_next %}
				<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
			  {% else %}
				<li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
			  {% endif %}
			</ul>
		  {% endif %}

	{% else %}
		  Sorry, there was an error fetching the list of blocks. Please try again later.
	{% endif %}
		</div>
	  </div>

	  <table class="table table-horizontal-bordered table-hover">
		<thead class="thead-light">
		  <tr>
			<th>Height</th>
			<th>Hash</th>
			<th>Age</th>
		  <th>Difficulty</th>
		  <th>PoW Algo</th>
			<th># Kernels</th>
			<th># Inputs</th>
			<th># Outputs</th>
		  </tr>
		</thead>
		<tbody>
		  {% for blk in block_list %}
			<tr>
			  <td><a href="/block/{{ blk.height }}" style="color:royalblue">{{ blk.height }}</a></td>
			  <td><a href="/block/{{ blk.hash }}" style="color:royalblue"><font face=monospace>{{ blk.hash }}</font></a></td>
			  <td>{{ blk.timestamp | shortnaturaltime }}</td>
			<td class="numeric">{{ blk.target_difficulty | intcomma }}</td>
			<td>
			  {% if blk.edge_bits == 29 %}
			  cuckARoo29
			  {% elif blk.edge_bits == 31 %}
			  cuckAToo31
			  {% elif blk.edge_bits == 32 %}
			  cuckAToo32
			  {% endif %}
			  </td>
			  <td class="numeric" align="left">{{ blk.kernel_set.all.count }}</td>
			  <td class="numeric" align="left">{{ blk.input_set.all.count }}</td>
			  <td class="numeric" align="left">{{ blk.output_set.all.count }}</td>
			</tr>
		  {% endfor %}
		</tbody>
	  </table>
  {% else %}
	  <br><br>
	  <h1>Block Database is empty</h1>
	  <h2>Please run <code>./manage.py import_from_tip ...</code> to populate the database.</h2>
  {% endif %}
{% endblock %}

explorer/templates/explorer/blocks_by_height.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}
  <br>
  <br>

  <h2>Block {{ height }}</h2>

  <p>
	There was a fork in the blockchain resulting in several competing blocks at this height:
  </p>

  <table class="table table-horizontal-bordered table-hover">
	<thead class="thead-light">
	  <tr>
		<th>Hash</th>
		<th>Age</th>
		<th>Cumulative Difficulty</th>
		<th># kernel</th>
		<th># in</th>
		<th># out</th>
	  </tr>
	</thead>
	<tbody>
	  {% for blk in blocks %}
		<tr>
		  <td><a href="/block/{{ blk.hash }}">{{ blk.hash }}</a></td>
		  <td>{{ blk.timestamp | naturaltime}}</td>
		  <td>{{ blk.total_difficulty | intcomma }}</td>
		  <td>{{ blk.kernel_set.all.count }}</td>
		  <td>{{ blk.input_set.all.count }}</td>
		  <td>{{ blk.output_set.all.count }}</td>
		</tr>
	  {% endfor %}
	</tbody>
  </table>

{% endblock content %}

explorer/templates/explorer/fee_chart.html
{% extends "base.html" %}


{% block chart_loader_header %}
    <!-- code to include the highcharts and jQuery libraries goes here -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
	<script src="https://code.highcharts.com/highcharts.js"></script>
    <!-- load_charts filter takes a comma-separated list of id's where -->
    <!-- the charts need to be rendered to                             -->
	{% load chartit %}
	{{ feechart|load_charts:"containerfeechart" }}
{% endblock %}


{% block content %}
  <br>

  <div>
        <div class="tag-box tag-box-v2 box-shadow shadow-effect-1" style="margin-bottom: 0px; background-color: #FFFFFF;">
            <div id="containerfeechart" style="min-width: 1024px; height: 480px; margin: 0 auto">
            </div>
        </div>
  </div>

{% endblock %}

explorer/templates/explorer/search_results.html
{% extends "base.html" %}

{% load humanize %}

{% block content %}
  <br>
  <br>

  <h2>Search Results for "{{ q }}"</h2>

  {% if results %}
	<table class="table table-bordered table-hover">
	  <thead class="thead-light">
		<tr>
		  <th>Hash</th>
		  <th>Age</th>
		  <th>Cumulative Difficulty</th>
		  <th># Kernels</th>
		  <th># Inputs</th>
		  <th># Outputs</th>
		</tr>
	  </thead>
	  <tbody>
		{% for blk in results %}
		  <tr>
			<td><a href="/block/{{ blk.hash }}">{{ blk.hash }}</a></td>
			<td>{{ blk.timestamp | naturaltime}}</td>
			<td>{{ blk.total_difficulty | intcomma }}</td>
			<td>{{ blk.kernel_set.all.count }}</td>
			<td>{{ blk.input_set.all.count }}</td>
			<td>{{ blk.output_set.all.count }}</td>
		  </tr>
		{% endfor %}
	  </tbody>
	</table>
  {% else %}
	{% if q_isdigit %}
	  <p>
		We couldn't find a block at height <strong>{{ q }}</strong>.
	  </p>
	{% elif q|length < 6 %}
	  <p>
		Your search term <strong>{{ q }}</strong> is too short, please enter at least six characters if searching by hash.
	  </p>
	{% else %}
	  <p>
		We couldn't find any blocks starting with the hash <strong>{{ q }}</strong>.
	  </p>
	{% endif %}
  {% endif %}
{% endblock content %}